Add GET revision webmock
mrgutie8/metabase-ruby-rest-api pull request #43
Opened 2023-11-08 20:00 UTC by lmortiz6

2023-11-09 21:19 UTC, apassett requested changes
1.) Wrong it statement (this call does not fetch all segments)
2.) rubocop suggestions present - lint the code for this file

2023-11-10 02:03 UTC, lmortiz6 commented
@apassett apologies for the sloppiness

2024-01-20 02:56 UTC, grustia01 reviewed
lgtm

2024-01-23 02:19 UTC, grustia01 approved these changes

2024-01-23 02:22 UTC, apassett approved these changes

2024-01-23 02:24 UTC, merged