Us#93 detete subscription
mrgutie8/metabase-ruby-rest-api pull request #62
Opened 2023-11-16 23:36 UTC by apassett

2023-11-24 07:00 UTC, grustia01 commented on lib/metabase/endpoint/pulse.rb
> +      # @see https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apipulse
Delete subscription document url is https://github.com/metabase/metabase/blob/master/docs/api/pulse.md#delete-apipulseidsubscription

2023-11-26 01:49 UTC, mrgutie8 requested changes
see https://github.com/mrgutie8/metabase-ruby-rest-api/pull/62/files#r1404002971

2023-11-30 01:29 UTC, mrgutie8 approved these changes
lgtm

2023-12-02 23:04 UTC, apassett commented
Had to resolve conflicts with the dev branch please re-review

2023-12-17 03:16 UTC, merged